# Generated by Django 4.2 on 2023-04-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='posted_time',
            field=models.DateField(auto_now=True),
        ),
    ]
